<?php
/**
 * Dicionário de tradução da ÁREA DO CLIENTE (Sis_Ped).
 *
 * A chave é a própria frase em português (idioma padrão). Para 'en' e 'es',
 * a função t() (em config.php) busca aqui e cai de volta para o português
 * quando não há entrada. Idioma é resolvido por idiomaAtual() a partir do
 * cadastro do cliente. Produtos têm tradução própria nos cadastros e NÃO
 * passam por este dicionário.
 *
 * Placeholders: %s (sprintf, lado PHP) e %1..%4 (substituição no lado JS).
 */
return [

    'en' => [
        // Layout / navegação
        'Abrir menu'               => 'Open menu',
        'Trocar empresa'           => 'Switch company',
        'Cliente'                  => 'Customer',
        'Deseja realmente sair?'   => 'Do you really want to log out?',
        'Sair'                     => 'Log out',
        'Trocar Empresa'           => 'Switch Company',
        'Selecione o CNPJ para o qual deseja realizar o pedido:' => 'Select the company you want to order for:',
        'Atual'                    => 'Current',
        'Cancelar'                 => 'Cancel',
        'Confirmar'                => 'Confirm',
        'Menu'                     => 'Menu',
        'Área do Cliente'          => 'Customer Area',
        'Dashboard'                => 'Dashboard',
        'Novo Pedido'              => 'New Order',
        'Meus Pedidos'             => 'My Orders',
        'Financeiro'               => 'Finance',
        'Meu Perfil'               => 'My Profile',

        // Troca de senha
        'Defina sua nova senha'    => 'Set your new password',
        'Por segurança, no primeiro acesso é necessário alterar sua senha antes de continuar.' => 'For your security, you must change your password before continuing on first access.',
        'Nova Senha'               => 'New Password',
        'Confirmar Senha'          => 'Confirm Password',
        'Salvar nova senha'        => 'Save new password',
        'A senha deve ter pelo menos 4 caracteres.' => 'The password must be at least 4 characters long.',
        'As senhas não conferem.'  => 'The passwords do not match.',
        'Escolha uma senha diferente da senha padrão.' => 'Please choose a password different from the default one.',
        'Informe a nova senha.'    => 'Please enter the new password.',
        'Senha alterada com sucesso!' => 'Password changed successfully!',
        'Alterar Senha'            => 'Change Password',
        'Erro:'                    => 'Error:',

        // Status (statusBadge)
        'Aguardando Comercial'     => 'Awaiting Sales',
        'Aguardando Financeiro'    => 'Awaiting Finance',
        'Aguardando Faturamento'   => 'Awaiting Invoicing',
        'Faturado'                 => 'Invoiced',
        'Cancelado'                => 'Cancelled',
        'Ativo'                    => 'Active',
        'Inativo'                  => 'Inactive',
        'Aberto'                   => 'Open',
        'Pago'                     => 'Paid',
        'Vencido'                  => 'Overdue',
        'Aprovado'                 => 'Approved',
        'Pendente'                 => 'Pending',

        // Dashboard
        'Bônus de Material de Apoio Disponível!' => 'Support Material Bonus Available!',
        'Você possui'              => 'You have',
        'de Bônus MA para utilizar em produtos de Material de Apoio.' => 'in Support Material Bonus to use on Support Material products.',
        'Deseja utilizá-lo agora?' => 'Would you like to use it now?',
        'Não'                      => 'No',
        'Sim, utilizar agora'      => 'Yes, use it now',
        'Bem-vindo, %s!'           => 'Welcome, %s!',
        'Total de Pedidos'         => 'Total Orders',
        'Em Andamento'             => 'In Progress',
        'Faturados'                => 'Invoiced',
        'Valor Faturado'           => 'Invoiced Amount',
        'Bônus MA'                 => 'SM Bonus',
        'Clique para utilizar'     => 'Click to use',
        'Boletos Vencidos'         => 'Overdue Invoices',
        'Boletos em Aberto'        => 'Open Invoices',
        'Saldo a Pagar'            => 'Balance Due',
        'Cancelados'               => 'Cancelled',
        'Últimos Pedidos'          => 'Latest Orders',
        'Ver todos'                => 'View all',
        'Nº Pedido'                => 'Order No.',
        'Produto'                  => 'Product',
        'Data'                     => 'Date',
        'Qtd'                      => 'Qty',
        'Valor'                    => 'Amount',
        'Status'                   => 'Status',
        'Nenhum pedido encontrado.' => 'No orders found.',
        'Você tem'                 => 'You have',
        'produto(s) salvos no carrinho do acesso anterior.' => 'product(s) saved in your cart from a previous session.',
        'Continuar pedido'         => 'Continue order',

        // Meus Pedidos
        'Todos'                    => 'All',
        'itens'                    => 'items',
        'Tipo'                     => 'Type',
        'Ação'                     => 'Action',
        'Venda'                    => 'Sale',
        'Bonificacao'              => 'Bonus',
        'Bonificação'              => 'Bonus',
        'Detalhes'                 => 'Details',
        '%s pedido(s) encontrado(s).' => '%s order(s) found.',

        // Financeiro
        'Seus títulos e boletos a receber' => 'Your receivables and invoices',
        'Total'                    => 'Total',
        'Em Aberto'                => 'Open',
        'Documento'                => 'Document',
        'Desconto'                 => 'Discount',
        'Líquido'                  => 'Net',
        'Emissão'                  => 'Issue',
        'Vencimento'               => 'Due Date',
        'Pagamento'                => 'Payment',
        'Situação'                 => 'Status',
        'Nenhum título encontrado.' => 'No records found.',

        // Perfil
        'Contato e Endereço'       => 'Contact and Address',
        'E-mail'                   => 'E-mail',
        'login'                    => 'login',
        'Telefone 1'               => 'Phone 1',
        'Telefone 2'               => 'Phone 2',
        'CEP'                      => 'ZIP Code',
        'Endereço'                 => 'Address',
        'Número'                   => 'Number',
        'Complemento'              => 'Complement',
        'Bairro'                   => 'District',
        'Cidade'                   => 'City',
        'UF'                       => 'State',
        'País'                     => 'Country',
        'Para alterar seus dados, entre em contato com o suporte.' => 'To change your information, please contact support.',
        'Dados Cadastrais'         => 'Registration Data',
        'Código'                   => 'Code',
        'Razão Social'             => 'Company Name',
        'CNPJ'                     => 'Tax ID',
        'Supervisor'               => 'Supervisor',
        'Canal de Venda'           => 'Sales Channel',

        // Pedido (detalhe)
        'Produto inválido.'        => 'Invalid product.',
        'Pedido atualizado com sucesso!' => 'Order updated successfully!',
        'Edição não permitida para este pedido.' => 'Editing is not allowed for this order.',
        'Pedido inválido.'         => 'Invalid order.',
        'Pedido não encontrado.'   => 'Order not found.',
        'Aguardando análise do time Comercial.' => 'Awaiting review by the Sales team.',
        'Em análise pelo time Financeiro.' => 'Under review by the Finance team.',
        'Pedido aprovado e faturado.' => 'Order approved and invoiced.',
        'Pedido cancelado. Entre em contato com seu supervisor.' => 'Order cancelled. Please contact your supervisor.',
        'Pedido'                   => 'Order',
        'Voltar'                   => 'Back',
        'Informações'              => 'Information',
        'Tipo de Venda'            => 'Sale Type',
        'Data do Pedido'           => 'Order Date',
        'Total a Pagar'            => 'Total Due',
        'Valor Total'              => 'Total Amount',
        'Forma de Pagamento'       => 'Payment Method',
        'Crédito Aplicado'         => 'Applied Credit',
        'Desconto Pix (5%)'        => 'Pix Discount (5%)',
        'Observações'              => 'Notes',
        'Itens do Pedido'          => 'Order Items',
        'Preço Unit.'              => 'Unit Price',
        'Total'                    => 'Total',
        'Subtotal:'                => 'Subtotal:',
        'Crédito aplicado:'        => 'Applied credit:',
        'Desconto Pix (5%):'       => 'Pix Discount (5%):',
        'Total a Pagar:'           => 'Total Due:',
        'Total Geral:'             => 'Grand Total:',
        'Status do Pedido'         => 'Order Status',
        'Editar Pedido'            => 'Edit Order',
        'Criado em:'               => 'Created on:',

        // Selecionar / trocar empresa
        'Seleção inválida.'        => 'Invalid selection.',
        'Empresa não encontrada.'  => 'Company not found.',
        'Selecionar Empresa'       => 'Select Company',
        'Olá, %s.'                 => 'Hello, %s.',
        'Com qual CNPJ deseja realizar o pedido?' => 'Which company would you like to order for?',
        'Continuar'                => 'Continue',
        'Sair e entrar com outra conta' => 'Log out and sign in with another account',

        // Bonificação selecionável
        'Campanha %s: valor selecionado excede o limite.' => 'Campaign %s: the selected amount exceeds the limit.',
        'Campanha %s: quantidade selecionada excede o limite.' => 'Campaign %s: the selected quantity exceeds the limit.',
        'Escolha seus bônus'       => 'Choose your bonus',
        'Escolha seus produtos bônus' => 'Choose your bonus products',
        'Seu pedido participa de campanha(s) de bonificação. Escolha os produtos bônus respeitando o limite de cada campanha.' => 'Your order qualifies for bonus campaign(s). Choose the bonus products within each campaign limit.',
        'un.'                      => 'pcs',
        'Campanha'                 => 'Campaign',
        'Limite:'                  => 'Limit:',
        'Selecionado:'             => 'Selected:',
        'Limite excedido'          => 'Limit exceeded',
        'Preço unit.'              => 'Unit price',
        'Múlt.'                    => 'Mult.',
        'Quantidade'               => 'Quantity',
        'Qtd. Total'               => 'Total Qty',
        'Concluir sem escolher bônus? Você não poderá selecionar depois.' => 'Finish without choosing a bonus? You will not be able to select it later.',
        'Pular'                    => 'Skip',
        'Confirmar bônus'          => 'Confirm bonus',
        // Pop-up do bônus de Exportação
        'Bônus de Exportação'      => 'Export Bonus',
        'Seu pedido de venda foi finalizado. Veja como o seu bônus foi calculado:' => 'Your sales order has been completed. See how your bonus was calculated:',
        'Valor da venda'           => 'Sale amount',
        'Percentual de bônus'      => 'Bonus percentage',
        'Bônus para escolher'      => 'Bonus to choose',
        'Escolha abaixo os produtos bônus até este valor para concluir.' => 'Choose the bonus products below up to this amount to finish.',
        'Escolher meus bônus'      => 'Choose my bonus',

        // PDF de confirmação
        'Outros'                   => 'Others',
        'Confirmação de Pedido'    => 'Order Confirmation',
        'Você foi bonificado!'     => 'You earned a bonus!',
        'Um pedido bonificado foi gerado com:' => 'A bonus order was generated with:',
        'Salvar / Imprimir PDF'    => 'Save / Print PDF',
        'Dados do Cliente'         => 'Customer Details',
        'CNPJ / CPF'               => 'Tax ID',
        'Cidade / Estado'          => 'City / State',
        'Cód. Produto'             => 'Product Code',
        'Cód. Barras'              => 'Barcode',
        'Qtd.'                     => 'Qty.',
        'Valor Total'              => 'Total Amount',
        'Subtotal'                 => 'Subtotal',
        'Total Geral do Pedido'    => 'Order Grand Total',
        'Forma de Pagamento:'      => 'Payment Method:',
        'Observações:'             => 'Notes:',
        'Sistema de Pedidos'       => 'Order System',
        'Gerado em'                => 'Generated on',

        // Novo pedido
        'Selecione uma forma de pagamento para continuar.' => 'Select a payment method to continue.',
        'Pedido não disponível para edição.' => 'Order not available for editing.',
        'Adicione ao menos um produto ao carrinho.' => 'Add at least one product to the cart.',
        'Linha'                    => 'Line',
        'Grupo'                    => 'Group',
        'Subgrupo'                 => 'Subgroup',
        'Todos os produtos'        => 'All products',
        'E'                        => 'AND',
        'OU valor ≥'               => 'OR amount ≥',
        'Valor ≥'                  => 'Amount ≥',
        'a partir de'              => 'from',
        'Informe as quantidades e clique em Carrinho para avançar' => 'Enter the quantities and click Cart to proceed',
        'Carrinho'                 => 'Cart',
        'Campanhas Ativas'         => 'Active Campaigns',
        'ou Valor'                 => 'or Amount',
        'Valor'                    => 'Amount',
        'Você escolhe (até %s):'   => 'You choose (up to %s):',
        'Brinde:'                  => 'Gift:',
        'Desconto de'              => 'Discount of',
        'Campanha atingida!'       => 'Campaign reached!',
        'Seu pedido atingiu a(s) campanha(s) abaixo. Confira os benefícios a que você tem direito:' => 'Your order has reached the campaign(s) below. Check the benefits you are entitled to:',
        'Escolha entre:'           => 'Choose among:',
        'Você recebe'              => 'You receive',
        'Você pode escolher até'   => 'You can choose up to',
        'campanha atingida %1×'    => 'campaign reached %1×',
        'Pedido de Bônus de Material de Apoio' => 'Support Material Bonus Order',
        'Apenas linhas de Material de Apoio disponíveis. Tipo de venda:' => 'Only Support Material lines available. Sale type:',
        'Saldo disponível'         => 'Available balance',
        'Linhas'                   => 'Lines',
        'Filtrar produto...'       => 'Filter product...',
        'Cod. Barras'              => 'Barcode',
        'Quantidade Total'         => 'Total Quantity',
        'Quantidade<br>Total'      => 'Total<br>Quantity',
        'Resumo do Pedido'         => 'Order Summary',
        'Confira os itens e finalize' => 'Review the items and finish',
        'Voltar aos produtos'      => 'Back to products',
        'Observação (opcional)'    => 'Notes (optional)',
        'Instruções especiais, prazo, etc.' => 'Special instructions, deadline, etc.',
        'Finalizar Pedido'         => 'Finish Order',
        'Avançar para Pagamento'   => 'Proceed to Payment',
        'Selecione como deseja pagar este pedido:' => 'Choose how you want to pay for this order:',
        '5% de desconto'           => '5% discount',
        'Pagamento à vista instantâneo — ganhe' => 'Instant upfront payment — get',
        'Boleto 30 Dias'           => 'Bank Slip 30 Days',
        '1 parcela — vencimento em 30 dias' => '1 installment — due in 30 days',
        'Boleto 30/60 Dias'        => 'Bank Slip 30/60 Days',
        '2 parcelas — 30 e 60 dias' => '2 installments — 30 and 60 days',
        'Boleto 30/60/90 Dias'     => 'Bank Slip 30/60/90 Days',
        '3 parcelas — 30, 60 e 90 dias' => '3 installments — 30, 60 and 90 days',
        'Pagamento via'            => 'Payment via',
        'desconto de'              => 'discount of',
        'sobre o valor total do pedido.' => 'on the total order amount.',
        'CRÉDITO DISPONÍVEL'       => 'AVAILABLE CREDIT',
        'Usar crédito no pedido'   => 'Use credit on this order',
        'Total disponível:'        => 'Total available:',
        'Será aplicado'            => 'Will apply',
        'de crédito neste pedido.' => 'of credit on this order.',
        'Avançar'                  => 'Proceed',
        'Limpar Carrinho'          => 'Clear Cart',
        // JS
        'Nenhum produto adicionado.' => 'No products added.',
        'Informe as quantidades na lista.' => 'Enter the quantities in the list.',
        'Deseja remover todos os produtos do carrinho?' => 'Remove all products from the cart?',
        'Adicione pelo menos um produto ao carrinho.' => 'Add at least one product to the cart.',
        'O valor do pedido (%1) ultrapassa o saldo disponível de Bônus MA (%2).' => 'The order amount (%1) exceeds the available Support Material Bonus balance (%2).',
        'O valor do pedido (%1) ultrapassa o saldo de Bônus MA (%2).' => 'The order amount (%1) exceeds the Support Material Bonus balance (%2).',
        'Reduza a quantidade dos produtos para continuar.' => 'Reduce the product quantities to continue.',
        'Reduza a quantidade para continuar.' => 'Reduce the quantity to continue.',
        'Total Geral'              => 'Grand Total',
        'Processando...'           => 'Processing...',
        'Neste pedido não há diferença disponível entre o valor do pedido e o detalhamento fiscal%1, portanto não é possível aplicar crédito. O pedido seguirá sem uso de crédito.' => 'There is no available difference between the order amount and the tax breakdown%1 for this order, so credit cannot be applied. The order will proceed without using credit.',
        ' (já considerando o desconto Pix)' => ' (already considering the Pix discount)',
        "Você tem %1 de crédito, mas neste pedido só pode usar %2 (diferença entre o valor do pedido e o detalhamento fiscal%3).\n\nDeseja usar %2 e manter %4 para outro pedido?" => "You have %1 in credit, but on this order you can only use %2 (difference between the order amount and the tax breakdown%3).\n\nUse %2 and keep %4 for another order?",
        ', já descontado o Pix'    => ', with the Pix discount already deducted',
    ],

    'es' => [
        // Layout / navegação
        'Abrir menu'               => 'Abrir menú',
        'Trocar empresa'           => 'Cambiar empresa',
        'Cliente'                  => 'Cliente',
        'Deseja realmente sair?'   => '¿Desea realmente salir?',
        'Sair'                     => 'Salir',
        'Trocar Empresa'           => 'Cambiar Empresa',
        'Selecione o CNPJ para o qual deseja realizar o pedido:' => 'Seleccione la empresa para la cual desea realizar el pedido:',
        'Atual'                    => 'Actual',
        'Cancelar'                 => 'Cancelar',
        'Confirmar'                => 'Confirmar',
        'Menu'                     => 'Menú',
        'Área do Cliente'          => 'Área del Cliente',
        'Dashboard'                => 'Panel',
        'Novo Pedido'              => 'Nuevo Pedido',
        'Meus Pedidos'             => 'Mis Pedidos',
        'Financeiro'               => 'Finanzas',
        'Meu Perfil'               => 'Mi Perfil',

        // Troca de senha
        'Defina sua nova senha'    => 'Defina su nueva contraseña',
        'Por segurança, no primeiro acesso é necessário alterar sua senha antes de continuar.' => 'Por seguridad, en el primer acceso debe cambiar su contraseña antes de continuar.',
        'Nova Senha'               => 'Nueva Contraseña',
        'Confirmar Senha'          => 'Confirmar Contraseña',
        'Salvar nova senha'        => 'Guardar nueva contraseña',
        'A senha deve ter pelo menos 4 caracteres.' => 'La contraseña debe tener al menos 4 caracteres.',
        'As senhas não conferem.'  => 'Las contraseñas no coinciden.',
        'Escolha uma senha diferente da senha padrão.' => 'Elija una contraseña distinta de la predeterminada.',
        'Informe a nova senha.'    => 'Ingrese la nueva contraseña.',
        'Senha alterada com sucesso!' => '¡Contraseña cambiada con éxito!',
        'Alterar Senha'            => 'Cambiar Contraseña',
        'Erro:'                    => 'Error:',

        // Status (statusBadge)
        'Aguardando Comercial'     => 'Esperando Comercial',
        'Aguardando Financeiro'    => 'Esperando Finanzas',
        'Aguardando Faturamento'   => 'Esperando Facturación',
        'Faturado'                 => 'Facturado',
        'Cancelado'                => 'Cancelado',
        'Ativo'                    => 'Activo',
        'Inativo'                  => 'Inactivo',
        'Aberto'                   => 'Abierto',
        'Pago'                     => 'Pagado',
        'Vencido'                  => 'Vencido',
        'Aprovado'                 => 'Aprobado',
        'Pendente'                 => 'Pendiente',

        // Dashboard
        'Bônus de Material de Apoio Disponível!' => '¡Bono de Material de Apoyo Disponible!',
        'Você possui'              => 'Usted tiene',
        'de Bônus MA para utilizar em produtos de Material de Apoio.' => 'en Bono MA para usar en productos de Material de Apoyo.',
        'Deseja utilizá-lo agora?' => '¿Desea utilizarlo ahora?',
        'Não'                      => 'No',
        'Sim, utilizar agora'      => 'Sí, usar ahora',
        'Bem-vindo, %s!'           => '¡Bienvenido, %s!',
        'Total de Pedidos'         => 'Total de Pedidos',
        'Em Andamento'             => 'En Curso',
        'Faturados'                => 'Facturados',
        'Valor Faturado'           => 'Monto Facturado',
        'Bônus MA'                 => 'Bono MA',
        'Clique para utilizar'     => 'Haga clic para usar',
        'Boletos Vencidos'         => 'Recibos Vencidos',
        'Boletos em Aberto'        => 'Recibos Abiertos',
        'Saldo a Pagar'            => 'Saldo a Pagar',
        'Cancelados'               => 'Cancelados',
        'Últimos Pedidos'          => 'Últimos Pedidos',
        'Ver todos'                => 'Ver todos',
        'Nº Pedido'                => 'N.º Pedido',
        'Produto'                  => 'Producto',
        'Data'                     => 'Fecha',
        'Qtd'                      => 'Cant',
        'Valor'                    => 'Importe',
        'Status'                   => 'Estado',
        'Nenhum pedido encontrado.' => 'No se encontraron pedidos.',
        'Você tem'                 => 'Usted tiene',
        'produto(s) salvos no carrinho do acesso anterior.' => 'producto(s) guardados en el carrito de la sesión anterior.',
        'Continuar pedido'         => 'Continuar pedido',

        // Meus Pedidos
        'Todos'                    => 'Todos',
        'itens'                    => 'ítems',
        'Tipo'                     => 'Tipo',
        'Ação'                     => 'Acción',
        'Venda'                    => 'Venta',
        'Bonificacao'              => 'Bonificación',
        'Bonificação'              => 'Bonificación',
        'Detalhes'                 => 'Detalles',
        '%s pedido(s) encontrado(s).' => '%s pedido(s) encontrado(s).',

        // Financeiro
        'Seus títulos e boletos a receber' => 'Sus cuentas y recibos por cobrar',
        'Total'                    => 'Total',
        'Em Aberto'                => 'Abierto',
        'Documento'                => 'Documento',
        'Desconto'                 => 'Descuento',
        'Líquido'                  => 'Neto',
        'Emissão'                  => 'Emisión',
        'Vencimento'               => 'Vencimiento',
        'Pagamento'                => 'Pago',
        'Situação'                 => 'Estado',
        'Nenhum título encontrado.' => 'No se encontraron registros.',

        // Perfil
        'Contato e Endereço'       => 'Contacto y Dirección',
        'E-mail'                   => 'Correo',
        'login'                    => 'acceso',
        'Telefone 1'               => 'Teléfono 1',
        'Telefone 2'               => 'Teléfono 2',
        'CEP'                      => 'Código Postal',
        'Endereço'                 => 'Dirección',
        'Número'                   => 'Número',
        'Complemento'              => 'Complemento',
        'Bairro'                   => 'Barrio',
        'Cidade'                   => 'Ciudad',
        'UF'                       => 'Estado',
        'País'                     => 'País',
        'Para alterar seus dados, entre em contato com o suporte.' => 'Para cambiar sus datos, póngase en contacto con soporte.',
        'Dados Cadastrais'         => 'Datos de Registro',
        'Código'                   => 'Código',
        'Razão Social'             => 'Razón Social',
        'CNPJ'                     => 'CNPJ',
        'Supervisor'               => 'Supervisor',
        'Canal de Venda'           => 'Canal de Venta',

        // Pedido (detalhe)
        'Produto inválido.'        => 'Producto no válido.',
        'Pedido atualizado com sucesso!' => '¡Pedido actualizado con éxito!',
        'Edição não permitida para este pedido.' => 'No se permite editar este pedido.',
        'Pedido inválido.'         => 'Pedido no válido.',
        'Pedido não encontrado.'   => 'Pedido no encontrado.',
        'Aguardando análise do time Comercial.' => 'Esperando revisión del equipo Comercial.',
        'Em análise pelo time Financeiro.' => 'En revisión por el equipo de Finanzas.',
        'Pedido aprovado e faturado.' => 'Pedido aprobado y facturado.',
        'Pedido cancelado. Entre em contato com seu supervisor.' => 'Pedido cancelado. Póngase en contacto con su supervisor.',
        'Pedido'                   => 'Pedido',
        'Voltar'                   => 'Volver',
        'Informações'              => 'Información',
        'Tipo de Venda'            => 'Tipo de Venta',
        'Data do Pedido'           => 'Fecha del Pedido',
        'Total a Pagar'            => 'Total a Pagar',
        'Valor Total'              => 'Importe Total',
        'Forma de Pagamento'       => 'Forma de Pago',
        'Crédito Aplicado'         => 'Crédito Aplicado',
        'Desconto Pix (5%)'        => 'Descuento Pix (5%)',
        'Observações'              => 'Observaciones',
        'Itens do Pedido'          => 'Artículos del Pedido',
        'Preço Unit.'              => 'Precio Unit.',
        'Total'                    => 'Total',
        'Subtotal:'                => 'Subtotal:',
        'Crédito aplicado:'        => 'Crédito aplicado:',
        'Desconto Pix (5%):'       => 'Descuento Pix (5%):',
        'Total a Pagar:'           => 'Total a Pagar:',
        'Total Geral:'             => 'Total General:',
        'Status do Pedido'         => 'Estado del Pedido',
        'Editar Pedido'            => 'Editar Pedido',
        'Criado em:'               => 'Creado el:',

        // Selecionar / trocar empresa
        'Seleção inválida.'        => 'Selección no válida.',
        'Empresa não encontrada.'  => 'Empresa no encontrada.',
        'Selecionar Empresa'       => 'Seleccionar Empresa',
        'Olá, %s.'                 => 'Hola, %s.',
        'Com qual CNPJ deseja realizar o pedido?' => '¿Con qué empresa desea realizar el pedido?',
        'Continuar'                => 'Continuar',
        'Sair e entrar com outra conta' => 'Salir e ingresar con otra cuenta',

        // Bonificação selecionável
        'Campanha %s: valor selecionado excede o limite.' => 'Campaña %s: el importe seleccionado excede el límite.',
        'Campanha %s: quantidade selecionada excede o limite.' => 'Campaña %s: la cantidad seleccionada excede el límite.',
        'Escolha seus bônus'       => 'Elija sus bonos',
        'Escolha seus produtos bônus' => 'Elija sus productos de bonificación',
        'Seu pedido participa de campanha(s) de bonificação. Escolha os produtos bônus respeitando o limite de cada campanha.' => 'Su pedido participa en campaña(s) de bonificación. Elija los productos de bonificación respetando el límite de cada campaña.',
        'un.'                      => 'un.',
        'Campanha'                 => 'Campaña',
        'Limite:'                  => 'Límite:',
        'Selecionado:'             => 'Seleccionado:',
        'Limite excedido'          => 'Límite excedido',
        'Preço unit.'              => 'Precio unit.',
        'Múlt.'                    => 'Múlt.',
        'Quantidade'               => 'Cantidad',
        'Qtd. Total'               => 'Cant. Total',
        'Concluir sem escolher bônus? Você não poderá selecionar depois.' => '¿Finalizar sin elegir bonificación? No podrá seleccionarla después.',
        'Pular'                    => 'Omitir',
        'Confirmar bônus'          => 'Confirmar bonificación',
        // Pop-up del bono de Exportación
        'Bônus de Exportação'      => 'Bono de Exportación',
        'Seu pedido de venda foi finalizado. Veja como o seu bônus foi calculado:' => 'Su pedido de venta fue finalizado. Vea cómo se calculó su bono:',
        'Valor da venda'           => 'Importe de la venta',
        'Percentual de bônus'      => 'Porcentaje de bono',
        'Bônus para escolher'      => 'Bono para elegir',
        'Escolha abaixo os produtos bônus até este valor para concluir.' => 'Elija abajo los productos de bono hasta este importe para finalizar.',
        'Escolher meus bônus'      => 'Elegir mis bonos',

        // PDF de confirmação
        'Outros'                   => 'Otros',
        'Confirmação de Pedido'    => 'Confirmación de Pedido',
        'Você foi bonificado!'     => '¡Recibió una bonificación!',
        'Um pedido bonificado foi gerado com:' => 'Se generó un pedido de bonificación con:',
        'Salvar / Imprimir PDF'    => 'Guardar / Imprimir PDF',
        'Dados do Cliente'         => 'Datos del Cliente',
        'CNPJ / CPF'               => 'Identificación Fiscal',
        'Cidade / Estado'          => 'Ciudad / Estado',
        'Cód. Produto'             => 'Cód. Producto',
        'Cód. Barras'              => 'Cód. Barras',
        'Qtd.'                     => 'Cant.',
        'Valor Total'              => 'Importe Total',
        'Subtotal'                 => 'Subtotal',
        'Total Geral do Pedido'    => 'Total General del Pedido',
        'Forma de Pagamento:'      => 'Forma de Pago:',
        'Observações:'             => 'Observaciones:',
        'Sistema de Pedidos'       => 'Sistema de Pedidos',
        'Gerado em'                => 'Generado el',

        // Novo pedido
        'Selecione uma forma de pagamento para continuar.' => 'Seleccione una forma de pago para continuar.',
        'Pedido não disponível para edição.' => 'Pedido no disponible para edición.',
        'Adicione ao menos um produto ao carrinho.' => 'Agregue al menos un producto al carrito.',
        'Linha'                    => 'Línea',
        'Grupo'                    => 'Grupo',
        'Subgrupo'                 => 'Subgrupo',
        'Todos os produtos'        => 'Todos los productos',
        'E'                        => 'Y',
        'OU valor ≥'               => 'O importe ≥',
        'Valor ≥'                  => 'Importe ≥',
        'a partir de'              => 'a partir de',
        'Informe as quantidades e clique em Carrinho para avançar' => 'Ingrese las cantidades y haga clic en Carrito para continuar',
        'Carrinho'                 => 'Carrito',
        'Campanhas Ativas'         => 'Campañas Activas',
        'ou Valor'                 => 'o Importe',
        'Valor'                    => 'Importe',
        'Você escolhe (até %s):'   => 'Usted elige (hasta %s):',
        'Brinde:'                  => 'Obsequio:',
        'Desconto de'              => 'Descuento de',
        'Campanha atingida!'       => '¡Campaña alcanzada!',
        'Seu pedido atingiu a(s) campanha(s) abaixo. Confira os benefícios a que você tem direito:' => 'Su pedido alcanzó la(s) campaña(s) a continuación. Vea los beneficios a los que tiene derecho:',
        'Escolha entre:'           => 'Elija entre:',
        'Você recebe'              => 'Usted recibe',
        'Você pode escolher até'   => 'Puede elegir hasta',
        'campanha atingida %1×'    => 'campaña alcanzada %1×',
        'Pedido de Bônus de Material de Apoio' => 'Pedido de Bono de Material de Apoyo',
        'Apenas linhas de Material de Apoio disponíveis. Tipo de venda:' => 'Solo líneas de Material de Apoyo disponibles. Tipo de venta:',
        'Saldo disponível'         => 'Saldo disponible',
        'Linhas'                   => 'Líneas',
        'Filtrar produto...'       => 'Filtrar producto...',
        'Cod. Barras'              => 'Cód. Barras',
        'Quantidade Total'         => 'Cantidad Total',
        'Quantidade<br>Total'      => 'Cantidad<br>Total',
        'Resumo do Pedido'         => 'Resumen del Pedido',
        'Confira os itens e finalize' => 'Revise los artículos y finalice',
        'Voltar aos produtos'      => 'Volver a los productos',
        'Observação (opcional)'    => 'Observación (opcional)',
        'Instruções especiais, prazo, etc.' => 'Instrucciones especiales, plazo, etc.',
        'Finalizar Pedido'         => 'Finalizar Pedido',
        'Avançar para Pagamento'   => 'Continuar al Pago',
        'Selecione como deseja pagar este pedido:' => 'Seleccione cómo desea pagar este pedido:',
        '5% de desconto'           => '5% de descuento',
        'Pagamento à vista instantâneo — ganhe' => 'Pago al contado instantáneo — obtenga',
        'Boleto 30 Dias'           => 'Boleto 30 Días',
        '1 parcela — vencimento em 30 dias' => '1 cuota — vencimiento en 30 días',
        'Boleto 30/60 Dias'        => 'Boleto 30/60 Días',
        '2 parcelas — 30 e 60 dias' => '2 cuotas — 30 y 60 días',
        'Boleto 30/60/90 Dias'     => 'Boleto 30/60/90 Días',
        '3 parcelas — 30, 60 e 90 dias' => '3 cuotas — 30, 60 y 90 días',
        'Pagamento via'            => 'Pago vía',
        'desconto de'              => 'descuento de',
        'sobre o valor total do pedido.' => 'sobre el importe total del pedido.',
        'CRÉDITO DISPONÍVEL'       => 'CRÉDITO DISPONIBLE',
        'Usar crédito no pedido'   => 'Usar crédito en el pedido',
        'Total disponível:'        => 'Total disponible:',
        'Será aplicado'            => 'Se aplicará',
        'de crédito neste pedido.' => 'de crédito en este pedido.',
        'Avançar'                  => 'Continuar',
        'Limpar Carrinho'          => 'Vaciar Carrito',
        // JS
        'Nenhum produto adicionado.' => 'Ningún producto agregado.',
        'Informe as quantidades na lista.' => 'Ingrese las cantidades en la lista.',
        'Deseja remover todos os produtos do carrinho?' => '¿Desea quitar todos los productos del carrito?',
        'Adicione pelo menos um produto ao carrinho.' => 'Agregue al menos un producto al carrito.',
        'O valor do pedido (%1) ultrapassa o saldo disponível de Bônus MA (%2).' => 'El importe del pedido (%1) supera el saldo disponible de Bono MA (%2).',
        'O valor do pedido (%1) ultrapassa o saldo de Bônus MA (%2).' => 'El importe del pedido (%1) supera el saldo de Bono MA (%2).',
        'Reduza a quantidade dos produtos para continuar.' => 'Reduzca la cantidad de productos para continuar.',
        'Reduza a quantidade para continuar.' => 'Reduzca la cantidad para continuar.',
        'Total Geral'              => 'Total General',
        'Processando...'           => 'Procesando...',
        'Neste pedido não há diferença disponível entre o valor do pedido e o detalhamento fiscal%1, portanto não é possível aplicar crédito. O pedido seguirá sem uso de crédito.' => 'En este pedido no hay diferencia disponible entre el importe del pedido y el detalle fiscal%1, por lo que no se puede aplicar crédito. El pedido continuará sin usar crédito.',
        ' (já considerando o desconto Pix)' => ' (ya considerando el descuento Pix)',
        "Você tem %1 de crédito, mas neste pedido só pode usar %2 (diferença entre o valor do pedido e o detalhamento fiscal%3).\n\nDeseja usar %2 e manter %4 para outro pedido?" => "Tiene %1 de crédito, pero en este pedido solo puede usar %2 (diferencia entre el importe del pedido y el detalle fiscal%3).\n\n¿Desea usar %2 y mantener %4 para otro pedido?",
        ', já descontado o Pix'    => ', con el descuento Pix ya deducido',
    ],

];
